#if SERVER
                                             
                              
                             
                                 
                                 

                        
                                  
                                      
                                           
                                                    

       
                                    

                                           
                                           

                                      

                                                   
                                              
             
#endif          

global const asset MU1_LEVIATHAN_MODEL = $"mdl/Creatures/leviathan/leviathan_kingscanyon_animated.rmdl"

#if SERVER
                                                        
                                                                                                                                                            

                                                                                                                           

                                                             
                                                               
                                                           
                                                             

                                                                                           

                                                                                       

                                                 
                                                  
                                               

                                                         
                                                          
                                                           
                                                           

                                                  
                                                                              
                                                                                                                       
                                                      

                                                

                  
                                              
                                           

                 
                                                                                        

                   
                                                            

                   
 
	     
	     
	      
	     
	      
	      

	      
 

                          
 
	              
	               
	              
	                           
 

                          
 
	                                       

	                 
	                 
	              
	              

	                                 
	                                  
	                                        

	                           

	         
	            

	                               
	                          
	                            
	                  
	                   
	                  
 
                               
 
	                         
	                         
	            
	                                        
	             
 

       
	                                                                                                                        
	                                                   
	                                                   
	                                                             
	                                                                                        
	                                                                                        

	                                                
	                                     

	                                
	                                
      

                                                   
                                             
 
	                     

		                            

		                                                                                     

		                                                  

		                                                                                                              
		                                                                                   
		                                                                                        

	                        

	                            
		                                           
 

                                   
 
	                                                                   
	                                                                      
	                                                                      

	                                                  
		                

	                            
		                   
 


                                      
 
	                                             
	                                                                              
 

                                  
 
	                                                                    
	                                                                       
		      

	                                                                         
	                          
	                                        
	                                                                                                             
	                                                       
	                                                                       
	                                                                              
 


                                                                                    
 
	                                                        
		      

	                 
	                                      

	                                                                                                             
 

                                                    
 
	                                                                              
	        

	                                                                                  
 

                                                                             
 
	          
	               
 

                                           
 
	                                                                                   
	                           
		      

	                               
	                                                                    

	                                                                                    
	                                                         
	                                                      
	                                                          
	                                              

	                  
	                                     

	                                                                                   
	                                          
	                                      
	 
		                            
		                                       
		                                                              
		                                   
	 

	                                                                    
	                                                                            

	                                                          
	                                                                                                                                        
 


                                                    
 
	                                                                                   
	                           
		      
	                                   
	                                                                                                 

	                                                   
	                                  
	                              
	                              
	                                  
	                              
	                                          
	                        

	                                                                                                        
	                                                                       
		                                         
			      

		                      
			                                                                                                                                       

		                                                            
	   
 

                              
 
	                                                                
	                                                                

	                                            
	                                  
	                                       

	                                                                                       
	                                                          
	                                                          

	                                                 
	                                                 

	                                                          
	                                              
	                                                            
	                                                             
	                                                       
	                                                                     

	                                                       
	                                           
	                                                         
	                                                        
	                                                       

	                                                        
	                                            
	                                                          
	                                                         
	                                                         

	                                                        
	                                            
	                                                          
	                                                         
	                                                        

	                                                        
	                                           
	                                                          
	                                                         
	                                                        

	                                                        
	                                           
	                                                          
	                                                         
	                                                       


	                                                           
	                                               
	                                                             
	                                                              
	                                                        
	                                                                      

	                                                          
	                                                
	                                                            
	                                                             
	                                                        
	                                                                     

	                                                                      
	                                                            
	                                                                        
	                                                                     
	                                                                     

	                                                                       
	                                                             
	                                                                         
	                                                                      
	                                                                     

	                                                                       
	                                                             
	                                                                         
	                                                                      
	                                                                     

	                                                                       
	                                                             
	                                                                         
	                                                                      
	                                                                      

	                                                                       
	                                                             
	                                                                         
	                                                                      
	                                                                        




	                                       
	 
		                                               

		                        
		                                                                                                                                           
		                                                                                                                                                                                  
		                                                                                                                                    
		                                                                                                                                  

		                                                            
			                                                                                                                                         

		                                                                                                                                       
		                                                                                                                                    

		                                                                

		                                                                                                           
		                                                                                                            

		                                                  
		                                                                                                                                               
		                                                                                                                                                        
		                                                                                                                                                          
		                                                                                                                                                          
		                                                                                                                                                          
		                                                                                                                                                          

		                                                                                                                                                  

		                                                                             

		                                       
		                                                                                   
		                                                                        
		                                                                                   

		                                       
		                                                                                    
		                                                                        
		                                                                                   

		                                       
		                                                                                     
		                                                                      
		                                                                                   

		                                       
		                                                                                     
		                                                                      
		                                                                                   

		                                        
		                                                                                    
		                                                                       
		                                                                                    

		                                        
		                                                                                    
		                                                                        
		                                                                                    

		                                        
		                                                                                    
		                                                                      
		                                                                                    

		                                        
		                                                                                     
		                                                                         
		                                                                                    
	 

	                                       
	 
		                                               

		                        
		                                                                                                                                           
		                                                                                                                                                                                       
		                                                                                                                                    
		                                                                                                                                  
		                                                            
			                                                                                                                                         
		                                                                                                                                       

		                                                                

		                                                                                                           

		                                                                                                                                                
		                                                                                                                                                                       
		                                                                                                                                                                          
		                                                                                                                                                                          
		                                                                                                                                                                          
		                                                                                                                                                                          

		                                                                             

		                                       
		                                                                                    
		                                                                      
		                                                                                   

		                                       
		                                                                                 
		                                                                     
		                                                                                   

		                                       
		                                                                                     
		                                                                      
		                                                                                   

		                                       
		                                                                                     
		                                                                      
		                                                                                   

		                                       
		                                                                                   
		                                                                       
		                                                                                   
	 

	                                        
	 
		                                    
	 

	                                    
		                                       
	    
		                                                       


	                                       
	 
		                          
			                                                                                
		    
			                                   
	 

	                                                              
	                                               
	 
		                                       
		                                
		                                                             
	 
 


                                                         
 
	                                              
	                                           
	                                            

	                                                      
	                                                                                

	                                         
	                                                                    
	                                        
	                                                                                    
	                                                                                    
	                                                                                                                
	                                                                                                                
	                                                                                               
	                                                                                               
	                                 

	                                                            
		                      

	                                    
	 
		                                            
	 
	    
	 
		                                                                                                                                              
	 
	                                                                                                                             

	                                        
	                                                                

	                                                                                                                                                                    
	                          
		                                   

	                                              
	                                                          

	                                        
		                                                    

	                                  

	                                        
	                                         

	                                                                                                                             
	                                                                                                                                          
	                                                 
	                                                 
	                                                 
	                                        

	                           
	                                                       
	                                                       

	                     
 

                                                                                                                                                                                                         
 
	                                                                                          
	                                                
	                                                                                      
	                                                     
	                        
	                                                           

	                                  
	                           
	                                                      

	                                             
	                     

	                                            
	           
 

                                      
 
	                      
 


                                   
 
	                             
 


                                   
 
	                             
 

                              

                                                                  
                                                                 
                                           

                                                                        
 
	                                                       
	                                                               
	 
		                                                                                                                                                 
		 
			                                                                                
			                                                 

			                   
			                                                               
			                                                                               
			                                              
				                                       
			                                             
			                                            

			                  
				                                                              

			                                                                               
			 
				                                                                                               
				 
					                  
						                  
					                                       
					                                                                                                                                  
					                                                                                       
				 
				    
				 
					                  
						                        
					                           
					                                           
				 
			 
		 

		      
	 

	                                                      
	                                                                                

	                                                      
	                           
		      

	                                                 

	                   

	 
		                                                              
		                                                                              
		                                             
			                                      
		                                            
		                                           
	 

	                  
		                                                        

	                                     

	                                                   
	                                  
	                                                                                                               
	 
		                                                                

		                                                
		                                                                
		                               
		 
			                                         
			        
		 

		                                                            
		                          
			        

		                   
		                                 
	 

	                         
	 
		                                 
		                        

		                                 
		                                                 
	 

	                                               

	                                   
	                                     
	                                 
	                                  

	                                                                                            
 

                                      
 
	                                        
	 
		                                                                                
		                                            
		                              
		                                        
	 
 

                                                                                                                                                                
 
	                                         

	                                                                                      
	                                                                                                                                                
	                                                                                                                
	              

	                           
		      

	                                                                                               
	 
		                  
			                                               
		      
	 

	                   
	                                                  
	 
		                  
			                                                                                                    
		      
	 

	                                                                                                                         
	 
		       
		                  
			                                       

		                               

		         
		                                                                                   
		 
			                            
		 
		    
		 
			                           

			                                        

			                                                                    
			                                                                                                                    
			                                                         
			 
				                                      
					        
				                                                                                                                     
				                                                                          
				 
					                                              
					                                                                             
					     
				 
			 
		 

		                          
		                                                                 

		                                    
		 
			                                            
			                                        
			                                                                  
		 
		    
		 
			                                                                                                                                                   
			                                                                            
			                                                                   
		 

		                    
		                                      
		                                 

		      
	 

	                                                                                               

	                                                                                                      
	 
		                                                                          
		 
			                  
				                                       

			        
			                                   
			                                                                

			                                                  
		 

		                                                                          
		                                                                                    

		                                          
		                          
			                                   
		                                                
			                                                                   
	 

	                                                                                                        
	 
		                  
			                                        

		        
		                                                                                

		                                                                   
		                                             
			                                      

		                                                                           
		                          
			                                   
		    
			                                                                   
		      
	 

	                  
		                                    
 

                                                                                                              
 
	                                                                                                  
	                           

	                                            
	                                      

	                                      

	                                         
	                                                                    

	                                          
		                                                  
 


                                                 
 
	                                  
	                                                           
	                                                    


	                                                      
	                                                      
	                                  

	                                                                                             
 

                                                                                                                                              
 
	                                                                                                    

	                                                                 
	                                              

	              
	                                                                                                            
	                                                                                                                               
	                                                                                    
	                                                                                                                                                                                                 
	                                             

	              
 

                                                                                          
 
	                                               
		                                        
	                                                    
		                                         

	                                               
		                                        
	                                                    
		                                         

	              
 

                                                       
 
	                                                                                

	                         
	                               
	          
	 
		                                 

		                                                                                               
			        

		         
		                                                                                   
			                            
		    
			                            

		                                                                 
	 
 

                                          
 
	                         

	              
	                                    
		                                         
	    
		                                          

	             

	                                       
		                                       
 

                                           
 

	                                                                                      
		           

	            
 

                                                      
 
	                                          
	                                        

	                                    
	                                                     
	                                             

	                             
	 
		                                  
		                                                                                

		                                                                                               
			     

		                          
		                                                                               

		                                        
		                          
			     

		                                    
		                              
	 
 

                                

                                                                                           
 
	                                                 
	 
		                                         
		                                                                      

		                                                                                  
		                                                                                                                         
		                                                      
	 
 


                                                                                          
 
	                               
	                                                 
	 
		                                         
		                                                                      

		                                                      
	 
 


                                                

                                                      
 
	                                                                                

	                                                        

	                                                                                        
	                                                                            
	                                                                        

	                                                                                            
	                                             

	                                            

	                        

	                                                
	                              
	                              

	                             
	                           

	                                      
	                                                                                                                            

	          
	 
		              
		                    
		                                 
		                           

		                 

		                                            
		                                                 
		 
			                 
			                         

			                                                                       
			                                                                                
			 
				                                  
					                                     
				                         
				                   
			 
		 
		    
		 
			                                     
		 

		                               
		                            
		 
			            
				                                
			                                         
			 
				                                                 
				        
			 

			                                                                               
			                                                                               

			                                                     
			                                                                                                                          

			                                                                                                        
			                                                                                                                

			                                                                
			                                                     
			                                                                                     
			 
				            
					                                             
				                                                 
				        
			 

			                                                         
			                                                                     

			                                                                          
		 
		    
		 
			                                
			                       
		 

		                                                 
		 
			                                  
			                                                                                                                  
			                                                                       
			 
				                                                                                   
				 
					                          
					                                               
					                                             
					            
						                                                                        
				 
				                                 
				 
					                                  
					 
						                                         
						                                                   
						                                        
					 
					                                                                       
					 
						                                         
					 
				 
				                                      
				 
					                
					                                              
					 
						                                    
						                                                 
						                    
							                                       
					 
				 
			 

			                  
			 
				                                                                                    
				                 
			 
		 

		                                                 
		                                                                     
		                                          
		                             
		                                 
		                                

		                                                     

		                                        
		                                          

		                    
		                                                                   
		                                                                                           

		                                                                                     
		                              
		                                                             
		                                                                                
		                                                         
		                                 
		                                 
		                                     
		                                                                              

		                                
		                                            
		                                   
			                                        
		                                         
			                                        
		    
			                                               

		                                         
		                          
			                                         
		                                
			                                         
		    
			                                       

		                                                                                                           
		                                                   

		            
			                                                                                                                                                                       

		                                          
		 
			                                                                                                                                                                                          
			                 
			                                                         
				                             
			                                                               
				                            
			    
				                                                

			                                                
			                                      
			                        
			                                 
			                               
		   

		                                                                                             
		                                                                                           

		       
	 
 

                                                                                                     
                                 
                                 
                         

                                                                                                                           
 
	                                                                                            

	                               
	                          
	 
		            
			                                                   
		            
	 

	                                              
	                                          
	                                              
	 
		            
			                                                
		            
	 

	                                                   
	                                           
	 
		            
			                                                
		            
	 

	                                           
	 
		                                                                                                              
		                              
		 
			            
				                                                   
			            
		 
	 

	                                         

	                          

	                                        
	                                   
	              
	 
		                                                   
		 
			            
				                                                  
			            
		 
	 

	            
		                                                  

	           
 

                                                                                                  
 
	                        

	                                                  
	                      

	                            

	                                                                                                        
	                                          
	 
		                                                                      
			        

		                                                                                
		                                                 
			                                              

		                              
		                                             

		                                                                           
		 
			                                                                               
			                                 
		 
		    
		 
			                                                  
		 

		                                                      
		                                                     
	 
 


                                                                 
 
	                                                
 

                                                                 
 
	                                                
 

                                                                      
 
	                                                     
 

                                                                      
 
	                                                     
 

                                                                              
 
	                                                                                              
	                                                            
	                                    
 



                                                                         
 
	                                                                                              

	                                   

	                                        
		                                                                                
	    
		                                                                                

	                                                
	                                           
	                                                     
	                                                     
	                                                 
	                                   
	                           
	                                
	                                     
	                                       
	                                  
	                                      
	                                    
	                                                      
	                                              
	                     

	                                 
	                             
 

                                                                         
 
	                                     
	                                                                                              
		      

	                     
	 
		                        
			      

		                                                                                                                                                                                                                                                               
			                      


		                                                              

		                                               
	 

	                                          

	                                                                                              
	 
		                                 

		                            
		 
			                                         

			                               
				                                                    

		 
	 

	                                                                                                                         
	 
		                                   
		                                                       
			                                                                                             
	 

	                      
		      

	                                           
		                                                                                                                                                             
	    
		                                                                                                                                                                     

	                     
	 
	                                  
	                                          

	                                                                                                                                                   
			                                                                                                                               
	 

 

                                               
 
	        

	                                                                              

	                        
		                 
 

                                                                                                                                                                                                                                                                     
 
	                                        

	                 
	                           

	                                                               
	 
		                                                                 

		                             
		 
			                      
			                       
		 
	 

	                  

 

                                                                          
 
	                     
		                                                                                   
 

                                                                          
 
	                     
		                                                                                 
 

                                                                            
 

	                                                                                 
		      

	                                                                            
 

                                                                                   
 
	                                      
	                                              
	                  
	          
	 
		                                              
		 
			                          
			                                                                                                      
			 
				                       
				        
			 
			     
		 

		                         
		 
			            
			                      
				     

			                                                                                                    
			                                
		 
		    
		 
			                         
		 
	 

	                                        
	 
		                                   
		                                                                         
		                                                                         
		                                                                        
		                                                                        
		                                                                         
		                                                                         
		                                                                        
		                                                                        

		                                                         

		                                    
		 
			                                
				        
			                           
			                         
		 
	 
 

                                                                  
 
	                                  

	                                              
	                                              

	                                                                                                               
	                                               
	                    

	                   

	                            

	        

	             
 

                                                                       
 
	                       
		      

	                                                      

	                           
		      

	                                                 
		      

	                                                                         
 

                                 
 
	                                                                           		                              		                       
	                                                                            	                              		                       
	                                                                           		                              		                       
	                                                                            	                              		                       
	                                                                         	 	                              		                       
	                                                                         	 	                              		                       
	                                                                         	                                  		                       
	                                                                         	                                  		                       
	                                                                         	                                  		                       
	                                                                         	                                  		                       
 

                                   
 
	                                                                   
 

       

                                    
 
	                                   

	                                                                                   
	                                                               
	                                                  

	        
	                                      
	                                                                  
	                          
 

                                           
 
	                                                                                                                      
	                                                                               
	                                                                            
	                 
	                                      
	                                   

	                              

	            
		                       
		 
			                                                                                        
		 
	 

	              
	 
		                                                                  
		                                  
		                         
		                                                       

		        
	 
 

                                           
 
	                                                                             
	                 
	                                      
	                                   

	                              

	            
		                        
		 
			                                                                                         
		 
	 

	              
	 
		                                                                  
		                                  
		                         
		                                                       


		        
	 
 

                                                   
 
	                                   
	                                                            
	                                         

	                                                           
	                                         

	                                                               
	                                 

	                                                              
	                                 
 

                                              
 
	                                                  
		                 

	                                    

	                                                                
	                                                                

	                                                          
	                                              
	                                                            
	                                                             
	                                                       
	                                                                     

	                                                       
	                                           
	                                                         
	                                                        
	                                                       

	                                                        
	                                            
	                                                          
	                                                         
	                                                         

	                                                        
	                                            
	                                                          
	                                                         
	                                                        

	                                                        
	                                           
	                                                          
	                                                         
	                                                        

	                                                        
	                                           
	                                                          
	                                                         
	                                                       


	                                                           
	                                               
	                                                             
	                                                              
	                                                        
	                                                                      

	                                                          
	                                                
	                                                            
	                                                             
	                                                        
	                                                                     

	                                                                      
	                                                            
	                                                                        
	                                                                     
	                                                                     

	                                                                       
	                                                             
	                                                                         
	                                                                      
	                                                                     

	                                                                       
	                                                             
	                                                                         
	                                                                      
	                                                                     

	                                                                       
	                                                             
	                                                                         
	                                                                      
	                                                                      

	                                                                       
	                                                             
	                                                                         
	                                                                      
	                                                                        




	                                       
	 
		                                                  
		                                                                                                                                               
		                                                                                                                                                        
		                                                                                                                                                          
		                                                                                                                                                          
		                                                                                                                                                          
		                                                                                                                                                          

		                                                                                                                                                  
	 

	                                       
	 
		                                                                                                                                                
		                                                                                                                                                                       
		                                                                                                                                                                          
		                                                                                                                                                                          
		                                                                                                                                                                          
		                                                                                                                                                                          

	 




 
                
#endif          