#if SERVER
                                    
#endif

#if CLIENT
global function ClientCodeCallback_MapInit
                     
global function ServerCallback_S17DisableTweakLight
      
#endif

global function CodeCallback_PreMapInit

                     

#if SERVER
       
                                      
                                          
                                                  
                                    
      
#endif

#if SERVER
                    
 
	                                 
	                           
	                                            
	                              
	                              
	                           
	                                
	                             
	                                  
 

                
 
	      			          
	      			                   
	                        
	                         
	                              
	                                 
	      			            
	      			                  
	                         
	                             
	                            
	                            
	      			             
	                                
	                                 
	      			               
	      			                 
	      			                      
	      			                      
	      			                      
	      			                      

	      			           

	                            
	                            

	                                    
	                           
	                           
	                             

	                                       
	                  
 
#endif

struct {
#if SERVER
	                    
	                    

	                     
	                     

	                             
	                             

	                                
	                                

	                        
	                        

	                              
	                              

	                      
	                      

	                         
	                         

	                         
	                         

	                            
	                            

	                                                                                                         
	                                                                                                                    

	                                         
	                            
	                            
#endif

	#if CLIENT
	bool isDoorUnlocked = false
	#endif
	                       
} file

#if SERVER
                                                  
                                                                
                                            
                                                        
                                                                        
                                    
                                            
                                                          
                                                        
                                                   
                                                           
                                                      
                                                                    
                                                                    
                                                                  
                                                        
                                                        

                                                         
                                                         

                                                                 
                                                                 
                                                                 
                                                                 
                                                                 
                                                                 

                                                                                         
                                                                                                 
                                                                                           

                                                                            
                                                                                                                               

                                                                                           
                                                                                                                

                                                            
                                                                                  
                                                                          

                                                                 
                                                                                                              

                                                     
                                                           

                                                                           
                                                                               

                                                                        
                                                                                              

                                                                                       
                                                                                                

                                                              
                                                                  
                                                                           
                                                                               

                                              
#endif

const string S17_REALMED_VAULT_PANEL_SCRIPTNAME = "RealmedSalhamLockedDoorPanel"
const string S17_TWEAK_LIGHT_SCRIPTNAME = "s17_chr_end_tweak_light"
      



#if SERVER
                                    
 
	                                                              
		      

                     
	                                                        
	                                                               
	                                                
	                                                   
	                                                  
	                                                
	                                                        
	                                                                                        
	                                                         

	                                                        

	                                 
	                                           
	                                     
	                                 
	                                    
	                                              
	                                       
	                                        

	                         
	                          
	                                        
	                                        

	                                              
	                                                
	                                                     
	                                                         
	                                      

	                        
	                                           
	                              
	                              

	                                      
	                                            
	                                     

	                                                                                         
      
	            
	                                              
 
#endif         

#if SERVER
                                               
 
	                                                          
 
#endif

#if SERVER
                                                       
 
 	                                           
	                                                                                                                                     
	                             
	                           

	                                                   

	                        
 
#endif

void function CodeCallback_PreMapInit()
{
	AddCallback_OnNetworkRegistration( OnNetworkRegistration )
}

void function OnNetworkRegistration()
{
                      
	if ( IsEventFinale() )
	{
		RegisterNetworkedVariable( "DatapadPickedUp", SNDC_PLAYER_EXCLUSIVE, SNVT_BOOL, false )
		Remote_RegisterClientFunction( "ServerCallback_S17DisableTweakLight" )
	}
       
}

#if CLIENT
void function ClientCodeCallback_MapInit()
{
                     
	AddCreateCallback( "prop_script", VaultPanelSpawned )
      
	SharedInit()
}

                     
void function ServerCallback_S17DisableTweakLight()
{
	array< entity > tweakLight = GetEntArrayByScriptName( S17_TWEAK_LIGHT_SCRIPTNAME )
	if ( tweakLight.len() == 1 )
	{
		if ( IsValid(tweakLight[0]) )
			tweakLight[0].SetTweakLightBrightness(0)
	}
}
      
#endif         


void function SharedInit()
{

}

                     
#if CLIENT
void function VaultPanelSpawned( entity ent )
{
	if ( ent.GetScriptName() != S17_REALMED_VAULT_PANEL_SCRIPTNAME )
		return

	AddEntityCallback_GetUseEntOverrideText( ent, VaultPanel_TextOverride )
	file.isDoorUnlocked = false
}

void function DisplayRuiForLootVaultPanel( entity ent, entity player, var rui, ExtendedUseSettings settings )
{
	RuiSetBool( rui, "isVisible", true )
	RuiSetImage( rui, "icon", settings.icon )
	RuiSetGameTime( rui, "startTime", Time() )
	RuiSetGameTime( rui, "endTime", Time() + settings.duration )
	RuiSetString( rui, "hintKeyboardMouse", settings.hint )
	RuiSetString( rui, "hintController", settings.hint )
}

string function VaultPanel_TextOverride( entity panel )
{
	entity player = GetLocalViewPlayer()
	string textOverride

	if ( file.isDoorUnlocked )
		return ""

	if ( player.GetPlayerNetBool( "DatapadPickedUp" ) )
	{
		entity heldGadget = player.GetNormalWeapon( WEAPON_INVENTORY_SLOT_GADGET )
		entity activeWeapon = player.GetActiveWeapon( eActiveInventorySlot.mainHand )

		if ( IsValid( heldGadget ) && (heldGadget == activeWeapon) )
		{
			return ""
		}

		if( IsControllerModeActive() )
		{
			int useSurvivalSlotButton = GetConVarInt("gamepad_toggle_survivalSlot_to_weaponInspect")

			if ( useSurvivalSlotButton == 0 )                                         
				return "#S17CR_EQUIP"
			else
				return "#S17CR_EQUIP_NO_BIND"
		}
		else
			return "#S17CR_EQUIP_PC"
	}

	return "#S17CR_LOCKED"
}

#endif

#if SERVER || CLIENT
void function VaultPanel_OnUse( entity panel, entity player, int useInputFlags )
{
	if ( !IsBitFlagSet( useInputFlags, USE_INPUT_LONG ) )
		return

	if ( !player.GetPlayerNetBool( "DatapadPickedUp" ) )
		return

	#if CLIENT
	if ( file.isDoorUnlocked )
		return
	#endif

	ExtendedUseSettings settings

	settings.duration = 5.0
	settings.useInputFlag = IN_USE_LONG
	settings.successSound = "LootVault_Access"
	settings.successFunc = VaultPanelUseSuccess

	#if CLIENT
		settings.loopSound = "LootVault_StatusBar"
		settings.displayRuiFunc = DisplayRuiForLootVaultPanel
		settings.displayRui = $"ui/health_use_progress.rpak"
		settings.icon = $"rui/hud/gametype_icons/survival/data_knife"
		settings.hint = "#S17CR_UNLOCKING"
	#endif         

	#if SERVER
		                            
		                               
		                             
		                                    
	#endif         

	thread ExtendedUse( panel, player, settings )
}

void function VaultPanelUseSuccess( entity panel, entity player, ExtendedUseSettings settings )
{
	#if SERVER
	                   
	                  
	                                      
	                                                                        

	                                
	                              
	#endif

	#if CLIENT
	file.isDoorUnlocked = true
	#endif
}
#endif
      

#if SERVER
                               
 
 

                     
                                                   
 
	                          
		      

	                                 
	                                                            

	                                   

	                                     
	 
		                                               
		                            
		                            
		                             
		                           
		                           
		                                    
		                                        
		                   

		                            

		                                
			                              

		                               
			                      

		                                
			                       

		                                    
			                           

		                                        
		 
			                                   
			                               
		 

		                                
		 
			                           
			                       
		 

		                                     
			                            

		                                   
			                          

		                                       
			                              

		                                        
			                               

		                                 
		 
			                          
			                        
		 

		                                         
			                                 

		                                        
			                                

		                                    
		 
			                             
			                           
		 

		                                                                                                                         
		                        

		                      
		                        
		                     
		                         
		                              
		                          
		                       

		                                   
		 
			                       
				        

			                       
		 

	 
	    
	 
		                                                    
		                                                                                                                                      
	 
 

                                                                                                                                                       
 
	                                         
		      

	       
	                                                   
		      
	      

	                                                  
	                                                                           
	                                                      

	                                                     
	 
		                                                                                
		                                    
	 
 

                                            
 
	                      
	 
		                             
		                                                             
		                                             
		 
			              
			                                      
			                      
			                        
			                     
			                       
			                         
			                       
			                          
			                              
		 
	   
 

                                           
 
	                    
		      

	                              
	 
		                 
			                                    
			                                    
			             
			     
		                  
			                                     
			                                     
			             
			     
		             
			                                             
			                                             
			             
			     
		                 
			                                        
			                                        
			             
			     
		                                
			                                                
			                                                
			             
			     
		                               
		                                
			                              
			     
		                           
			                               
			     
		                     
			                                      
			                                      
			             
			     
		                        
			                                         
			                                         
			             
			     
		                        
			                                            
			                                            
			             
			     
		                               
			                                         
			                                         
			             
			     
		                        
			                                              
			                                              
			             
			     
		                              
			                                            
			                                            
			     
		                              
			                                            
			                                            
			     
		                              
			                                            
			                                            
			     
		                              
			                                            
			                                            
			     
		                              
			                                            
			                                            
			     
		                              
			                                            
			                                            
			     
		        
			     
	 
 

                                        
 
	                                                                                                                        
	                                      
	                                    
	                                                          

	                                                                                                                                               
	                                    
	                                  
	                                            
	                                                                

	       
	                                                            
	 
		                                     
	 
	      

	                                                                                                                                                       
	                                    
	                                  
	                                                              

	                                                                                                                                                        
	                                      
	                                    
	                                                                  

	                                                                                                                                                                            
	                                           
	                                         
	                                                                            

	                                                                                                                                                                            
	                                           
	                                         
	                                                                            

	                                                                                                                                                                                
	                                           
	                                         
	                                                                            

	                                                                                                                                                                              
	                                           
	                                         
	                                                                            
 

                                                      
 
	                                        
		      

	                                                                 
		      

	                                                           
	                                                                                                                                                                         
	                                                                                         
	                                                                                                     
	                                                                                                           
 

                                              
 
	                                                               
		                                                           

	                                                                 
		                                                             

	                                                                      
		                                                                  

	                                                                      
		                                                                  

	                                                                      
		                                                                  

	                                                                      
		                                                                  
 

                                           
 
	                                                                                                                           
	                          
	                                                                                                             
	                                                        
	                                                                    
	                                                                             
	                                    
	                                  

	                                                           
 

                                         
 
	                                                                                                                                              
	                                    
	                                  

	                                                                 
 

                                        
 
	                             
	                                               
 

                                         
 
	                                                                                                                     
	                               
	                             
	                              
	                                                    
 

                                                  
 
	                                                                                                                                                   
	                               
	                             
	                              
	                                                             
 

                                            
 
	                                                                                                                             
	                               
	                             
	                                                       
 

                                               
 
	                                                                                                                                   
	                              
	                            

	                                                         

	                                                                                                                                                                
	                
	                               
	                             

	                                                           
 

                                       
 
	                                                                                                           
	                             
	                           

	                                                
 

                                          
 
	                                                                                                                                           
	                      
	                                                                                                         
	                                                    
	                                                               
	                                
	                              
	                       

	                                         

	                                                                                             
	                                  
	                                

	                                                    
	                                                          

	                                   
	 
		                       
			        

		                                   
			        

		                  
		                       
		                 
		                                                         
	 
 

                                                    
 
	                                                             

	                                                                 

	                                                         
	 
		                                                    
		                                                                        
		                                                                                                        
		                                                                  
		                              
	 
 

                                         
 
	                                   
	 
		                       
			        

		                                   
			        

		                       
		                                                         
	 
 

                                         
 
	                                                             

	        

	                                        
		      

	                                                              
	 
		                                                                       
	 

	                                                              
		                                                                                                          
 

                                                               
 
	                       
		      

	                           
		      

	                  
	                         
	 
		                         
		      
	 

	                    
		      
	                                                     
 


                                                
 
	                                  
	 
		                             
			                                                         
			     
		                           
			                                                         
			     
		                           
			                                                          
			     
		                            
			                                                           
			     
		                       
			                                                       
			     
		                       
			                                                       
			     
		                               
			                                                                 
			     
		                          
			                                                  
			     
		                          
			                                                  
			     
	 
 

                                                                  
 
	                                        
	 
		                              
		                                     
		 
			                                                                       
			 
				                                                                
				                                 
			 
		 
	 
 

                                                                  
 
	                                        
	 
		                              
		                                     
		 
			                                                                       
			 
				                                                                
				                                 
			 
		 
	 
 

                                                                         
 
	                                        
	 
		                                           
			      

		                                                    
		                                 
		 
			                                    
			                                                          
			                                           

			                                                             
			                                
			 
				                                                  
			 
		 
	 
 

                                                                                  
 
	                              

	                 
	                
	                                                       
	                                                                                                                              
	                                                                
	                                                                          
	                                                                                                                  
	                                                                      
	                                                 
	                            
	                                               

 

                                                                   
 
	                                                                             
	                               
	                                 

	       

	                                                                     

	      

	                         
		                                                                       
 

                                                                                        
 
	                    

	                                                                                                

	                                           
 

                                                             
 
	                          
		      

	                                                                         
	                      
	 
		                                              
		                                                       
	 
 

                                                                
 
	                                                                             
	                               
	                               

	                          
		      

       
	                                                            
	 
		            
			                               
			 
				                                   
				                  

				                                                                       
				                                                                     
				                                          

				                                                         
				                                                            

				                                                                        

				                                 
			 
		 
	 
      

	                               

	                                        

	                                                         
	                                                      

	                                        
	                                                            
	                               
	                                                     
	                                      
	                        


	                                 
	                                                        
	                                                                                                            
	                                                    

	         

	                          
		      

	                                     

	        

	                          
		      

	       
		                                                            
		 
			                                       
			      
		 
	      

	                            
	 
		                                  
	 
	    
	 
		                           
		                                
	 
 

                                                    
 
	                      
		      

	                              

	                                        
		      

	                                                

	                                                                           
	                    

	                          
		                                                

	                                                         
	 
		                                  
		                                                                             
	 

	                                           
	 
		                                                          
		                                           
		      
	 

	                                                      
	                                                         

	                                          
	 

		                                                                              

		                                                             
		                                           
		 
			                                                    
		 
		    
		 
			                                                    
		 
	 

	                                           
	 
		                                                                              

		                                                                 
		                                                    
		                                                
	 
	    
	 
		                                                                 
		                                                    
		                                              
	 

	                                           
	 
		                                                                        
	 

	                  
	                  

	                                               
	 
		                                 
			                                           
			                        
			     
		                                 
		                                 
			                                        
			                                        
			     
		                                 
			                                        
			                                        
			     
		                                 
			                                        
			                                        
			     
		                                 
		                                 
			                                        
			                                        
			     
		                                 
			                                        
			                                        
			     
	 

	                                           
	                            
 

                                               
 
	                              
	 
		                               
		                                    
		                              
		      
	 
 

                                           
 
	                              
	 
		                            
		                                  
		      
	 

	                                                                   
	                                                                        

	                                                                           
	                    

	                          
		                                                

	                                                         
	 
		                                  
		                                                                             
	 

	                        
	                                                      
	                                                   
	                                                  
	                                 
	                                            
	                                                
	                            
	                                                

	                                  
	                                     
 

                                                      
 
	                          
		      

	                                                                             
	                               

	            
		                       
		 
			                        
			 
				                                       
				                                 
				                              
			 

		 
	 

	       
		                                                            
			      
	      

	        

	                               
	                                            

	        

	                                            
	                                        
	                              
	                                     
	                                      
	                                            
	                              

	                 
	                                                               

	         
	                                   
	                                                     


	                                                                                                               

	                                        

	                                                               
	                                              
	                                 
	                              
	                                      

	                                                                                                          
	                                                    

	            
		                                    
		 
			                                   
			                     
		 
	 

	                                       
	                                                         
	                                                                     

	                                                                  
	                                                
	                                                    
	                                     
 

                                                                         
 
	                                               
		      

	                              

	                                                     
		      

	                                                     
	                                                                  
	                                 

	                                                      
	                                                         
	                                     
	                           
	                                                                              

	                                                             
	                                                    

	                                                                 
	                                                    
	                                              

	                                  
 

                                                                          
 
	                                               
		      

	                              

	                                                     
		      

	                                                     
	                                                                  
	                                 

	                                     
	                                                                              

	                                                                 
	                                                    
	                                                

	                                                                                       
	                                            
 

                                                                                        
 
	                         
		      

	                                                                             
	                               

	                       
		      

	          

	                         
		      

	                                       
 

                                                                           
 
	                                               
		      

	                              

	                                                      
		      

	                                                      
	                                                                  
	                                 

	                                                                                 
	                                                                               
	                                                                               
	                                                                        
	                                                                           

	                                             
	                                                                                       
 

                                                                       
 
	                                               
		      

	                              

	                                                    
		      

	                                                    

	                                                    
	                                                                    
 

                                                                       
 
	                                               
		      

	                              

	                                                    
		      

	                                                    

	                                                       
	                                                                    
 

                                                                                 
 
	                                               
		      

	                              

	                                                             
		      

	                                                             
	                                                        
		      

	                                                    

	                                                             
	                                                                  
	                                 

	                                               
	                                
 

                                                
 
	                          
		      

	                               

	                                                                             
	                               

	           

	                                    

	                                             

	                                        
	                              
	                               
	                                                                 
	                                              
	                                  

	                                 
	                                                        
	                                                         

	                        
	                                                
 	                                                        
	                                   
	                               
	                                  
	                                 
 

       
                                                         
 
	                                                                             
	 
		                                                                              
		                                              
	 

	                                                                
	                                                    

	                                                   
	                                
 


                                                                                                                                                                           
 
	                          
	                          

	                                            
	                                        
	                              
	                                     
	                                      
	                                            
	                              

	                                        


	                 
	                                                               

	         
	                                   

	                        
		                                                     


	                                                                                                               

	                                        

	                                                               
	                                              
	                                 
	                              
	                                      
	                                        

	                                                                                                          
	                                                    

	            
		                                    
		 
			                                   
			                     
		 
	 

	                                                                     
 

                                                                 
 
	                                                                                      
 

                                                   
 
	                                                         
	                                                            
	                                               
	                                                 
	                                                    
 
      

      
#endif         