globalize_all_functions

#if SERVER && DEV
                                                                                                                      
 
	                                                                                   
	                    
	 
		                                                                                     
		                                                                                                                                            
	 
	                
 


                                                                          
 
	                                                       
	                                                                                           
	                                                                                

	                                                                                                                       

	                                                           
 


                                                                           
 
	                                                       
	                                                                                           
	                                                                                
	                                                                                                                       


	                                                                                                        
	                                                                            

	                                                                                                                   

	                                                            
 


                                                                                           
 
	                                                                         
	                                                                                                         
	                                                                                                      
	                                                                                          
	                                                                                       

	                                                                   
	                                                               
	                                                       
	                                                   
 


                                                                                                                                                   
 
	                                                                                                                     
	                                                                                                         
	                                                                                                                         
	                                                                    
		                                                                                                                                          

	                                                                                                                
		                                                                                                                                                                                                                              
 

                                          
 
	                                     
	  
	                             
	                                                         
	                                                         
	                     								   
	                      							   
	                                                     
	                                                     
	                                                     
	                                                     
	                        		                           
	                              	                                             
	  
	                                                         
 

                                      
 

	                     
	                                          

	                                   

	                            

	                                                                                                    
	                                     
	                                     
	                                   

	                             
	                             

	                           
	                           
	                           

	                                 
	                                 
	                                 

	                            
	                                                              
	                                                                               

	                                   
	                                   
	                                   
	                                   

	                            
	                              
	                                        
	                                          
	                                      


	        
	                           
	                                                             
	                  


	                                                              
	                                           
	                                                       

	                                                   
	                                                    

	                                            
	 
		                                            
	 

	                                                      
 





                                                                                                     
 
	                                             
	 
		                                                                                                                     

		                                                                                     
		                                                            

		                             
		 
			                                                  
		 

		                                                                                                                                                                                                                                                             

		                                                                                                              
		                                
		 
			                                   

			                                                                                                                 
				                                                                                                                                                                                                                               
		 

		                                  
	 
 


                                                       
 
	                                                    
	                                                           
	                                                  
	                                                             
	                                                                
	                                               
 


                                                                         
 
	                                             
	 
		                                                         
		                                                              
		                                                          
		                                                              
	 
 


                                                                              
 
	                                             
	 
		                     
		 
			                                                       
			                                                                                          
			                                                                                                                               

			                                                                                                    
			                                                                                
			                                                                                                          
		 
		    
		 
			                                                                                                                 
			 
				                                                                  
				                                                                                                 
				                                                                                                   
			 
		 

		                                                             
		                                                                                                                                                                                             
	 
 

                                                                    


	                                                     

	                     
	                    
	                                                  
	 
		                                    
		                                                 
		 
			                                                  
			                                                                                                       
		 
	 


	                                                          
	                                                                              
	                                                                           
 

                                                                


	                                                     

	                     
	                    
	                                                  
	 
		                                    
		                                              
		 
			                                                   
			                                                                                                       
		 
	 
	                                                          
	                                                                              
	                                                                           
 

                                                                                                                            
 
	                                            
	 
		                                                   
		                                                                             
	 
 

                                                                                                                      
 
	                                            
	 
		                                           
		                                                                             
	 
 

                                                                                                                              
 
	                                            
	 
		                                                     
		                                                                             
	 
 

                                      
 
	                                                     

	                                         
	                                                  
	 
		                                           
		                                                                                          
	 

	                                        
	                                                  
	 
		                                           
		                                                                                          
	 
 

                                                   
 
	                                                                                                                
 

                                                                                                                                                                                                                      
		                                                                                                                                                                      
 
	                 
	 
		                                                                          
		      
	 

	                
	                                                                                

	                     
	                                                           

	                                             

	                                   

	                                                                                                   
	                                                                                                    
	                                          
	                                               
	                                   

	                                            
	                                              
	                                                    
	                                                
	                                                      

	                   

	                           
	                                  
	 
		                                                     
		             
	 
	                                      
	 
		                                                         
		             
	 
	                                       
	 
		                                                          
		             
	 

	                                                                 
	                                                                   
	                                                                         
	                                                                     
	                                                                           

                                 
	                             

	                           
	                           
	                           

	                                                           
	                                                             
	                                                                   

	                                    
	                                                              
	                                                                               

	                                   
	                                   
	                                   
	                                   

	                            
	                              
	                                        
	                                          
	                                      

	        
	                                 
	                                                             
	                  

	                                                    
	 
		                            
		                                        
	 

	       
		                                                                                                                       
	      

	                                                       
 


                                                                                                                                                                                                                      
		                                                    
 
	                 
	 
		                                                                          
		      
	 

	                
	                                                                                

	                     
	                                          

	                                             

	                                   
	                            
	                                                                                                  
	                                                                                                    
	                                     
	                                     
	                                   

	                                            
	                                              
	                                                    
	                                                
	                                                      

	                   

	                           
	                                  
	 
		                                                     
		             
	 
	                                      
	 
		                                                         
		             
	 
	                                       
	 
		                                                          
		             
	 

	                                                                 
	                                                                   
	                                                                         
	                                                                     
	                                                                           

	                             
	                             

	                           
	                           
	                           

	                                                           
	                                                             
	                                                                   

	                                    
	                                                              
	                                                                               

	                                   
	                                   
	                                   
	                                   

	                            
	                              
	                                        
	                                          
	                                      

	        
	                                 
	                                                             
	                  

	                                                    
	 
		                            
		                                        
	 

	       
		                                                                                                                       
	      

	                                         
 



                                                                                                                                                                                                                   
		                                                                                                                                          
 
	                 
	 
		                                                                          
		      
	 

	                
	                                                                                

	                     
	                                          

	                                             

	                                   

	                                                                                                  
	                                                                                                    
	                                          
	                                               
	                                   

	                                            
	                                              
	                                                    
	                                                
	                                                      

	                   

	                           
	                                  
	 
		                                                     
		             
	 
	                                      
	 
		                                                         
		             
	 
	                                       
	 
		                                                          
		             
	 

	                                                                 
	                                                                   
	                                                                         
	                                                                     
	                                                                           

	                             
	                             

	                           
	                           
	                           

	                                                           
	                                                             
	                                                                   

	                                    
	                                                              
	                                                                               

	                                   
	                                   
	                                   
	                                   

	                            
	                              
	                                        
	                                          
	                                      

	        
	                                 
	                                                             
	                  

	                                                    
	 
		                            
		                                        
	 

	       
		                                                                                                                       
	      

	                                                        
	                                                      
	                                                            

	                                             

	                                                          

	                                                                                                 
 


                                                                                                       
 
	                 
	 
		                                                                          
		      
	 

	                
	                                                                                

	                                   

	                               
	                                                                               

	                                
	                                
	                                

	                                                                                                                                                                                 
	                                             
	                                                                                                                                                                                  
 

#endif          

#if DEV
void function DEV_script_ranked_debug ( string message,int indent = 0 )
{

	string tabs = ""

	for (int i = 0; i < indent; i++)
	{
		tabs += "\t"
	}

	if( GetConVarBool( "script_ranked_debug" ) )
	{
		printf ("script_ranked_debug:" + tabs + " " + message )
	}
}

void function PrintRankLadderPointsBreakdown ( RankLadderPointsBreakdown data , int indent = 0, string memo = "")
{

	DEV_script_ranked_debug ( "------------------------------------------------------", indent )
	DEV_script_ranked_debug ( "-----------PrintRankLadderPointsBreakdown() start ----", indent )
	DEV_script_ranked_debug ( "------------------------------------------------------", indent )

	indent++

	if ( memo != "" )
	{
		DEV_script_ranked_debug ( "memo:" + memo, indent++ )
	}

	DEV_script_ranked_debug ( "wasInProvisonalGame: " + data.wasInProvisonalGame, indent )
	DEV_script_ranked_debug ( "wasAbandoned: " + data.wasAbandoned, indent )
	DEV_script_ranked_debug ( "lossForgiveness: " + data.lossForgiveness , indent)
	DEV_script_ranked_debug ( "damage: " + data.damage , indent)
	DEV_script_ranked_debug ( "knockdown " + data.knockdown, indent )
	DEV_script_ranked_debug ( "knockdownAssist: " + data.knockdownAssist , indent)
	DEV_script_ranked_debug ( "kills: " + data.kills, indent )
	DEV_script_ranked_debug ( "assists: " + data.assists, indent)
	DEV_script_ranked_debug ( "participation: " + data.participation, indent )
	DEV_script_ranked_debug ( "killsUnique: " + data.killsUnique, indent)
	DEV_script_ranked_debug ( "assistUnique: " + data.assistUnique, indent)
	DEV_script_ranked_debug ( "participationUnique: " + data.participationUnique, indent)

	DEV_script_ranked_debug ( "placement: " + data.placement, indent)
	DEV_script_ranked_debug ( "placementScore: " + data.placementScore, indent)

	                                                          
	                                                                        
	                                                                    
	                                                                        

	DEV_script_ranked_debug ( "killBonus: " + data.killBonus, indent)
	DEV_script_ranked_debug ( "convergenceBonus: " + data.convergenceBonus, indent)
	DEV_script_ranked_debug ( "skillDiffBonus: " + data.skillDiffBonus, indent)

	DEV_script_ranked_debug ( "provisionalMatchBonus: " + data.provisionalMatchBonus, indent)

	DEV_script_ranked_debug ( "promotionBonus: " + data.promotionBonus, indent)
	DEV_script_ranked_debug ( "demotionPenality: " + data.demotionPenality, indent)
	DEV_script_ranked_debug ( "penaltyPointsForAbandoning: " + data.penaltyPointsForAbandoning, indent)
	DEV_script_ranked_debug ( "demotionProtectionAdjustment: " + data.demotionProtectionAdjustment, indent)
	DEV_script_ranked_debug ( "lossProtectionAdjustment: " + data.lossProtectionAdjustment, indent)

	DEV_script_ranked_debug ( "currentLP: " + data.startingLP, indent)
	DEV_script_ranked_debug ( "netLP: " + data.netLP, indent)
	DEV_script_ranked_debug ( "finalLP: " + data.finalLP, indent)

	DEV_script_ranked_debug ( "PrintRankLadderPointsBreakdown() end ----" , indent)
}
#endif